version: '3.8'
services: 

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes: 
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - 3000:80
    depends_on:
      - backend

volumes:
  db_data:

secrets:
  db_password:
    file: ./db/password.txt